package be.ac.umons.g06.gui.common;

public enum ViewName {
    LOGIN_VIEW,
    SIGNUP_VIEW,
    ACCOUNT_VIEW,
    EVENTS_VIEW,
    CHARTS_VIEW,
    WALLETS_VIEW,
    SETTINGS_VIEW,
    TRANSFER_VIEW,
    ACCOUNT_CREATION_VIEW,
    OPEN_WALLET_VIEW,
    MENU_VIEW,
    ADD_CUSTOMER_VIEW
}